In [18]:
import pandas as pd
import numpy as np
import seaborn as sns

from matplotlib import pyplot as plt
%matplotlib inline


In [19]:
df = pd.read_excel('data/satisfaction.xlsx', sheet_name=0, header=0, engine='openpyxl')

In [20]:
df.describe().T

count          mean           std   min  \
id                                 129880.0  64940.500000  37493.270818   1.0   
Age                                129880.0     39.427957     15.119360   7.0   
Flight Distance                    129880.0   1981.409055   1027.115606  50.0   
Seat comfort                       129880.0      2.838597      1.392983   0.0   
Departure/Arrival time convenient  129880.0      2.990645      1.527224   0.0   
Food and drink                     129880.0      2.851994      1.443729   0.0   
Gate location                      129880.0      2.990422      1.305970   0.0   
Inflight wifi service              129880.0      3.249130      1.318818   0.0   
Inflight entertainment             129880.0      3.383477      1.346059   0.0   
Online support                     129880.0      3.519703      1.306511   0.0   
Ease of Online booking             129880.0      3.472105      1.305560   0.0   
On-board service                   129880.0      3.465075      1.270836   0.0   
Leg room service                   129880.0      3.485902      1.292226   0.0   
Baggage handling                   129880.0      3.695673      1.156483   1.0   
Checkin service                    129880.0      3.340807      1.260582   0.0   
Cleanliness                        129880.0      3.705759      1.151774   0.0   
Online boarding                    129880.0      3.352587      1.298715   0.0   
Departure Delay in Minutes         129880.0     14.713713     38.071126   0.0   
Arrival Delay in Minutes           129487.0     15.091129     38.465650   0.0   

                                        25%      50%       75%       max  
id                                 32470.75  64940.5  97410.25  129880.0  
Age                                   27.00     40.0     51.00      85.0  
Flight Distance                     1359.00   1925.0   2544.00    6951.0  
Seat comfort                           2.00      3.0      4.00       5.0  
Departure/Arrival time convenient      2.00      3.0      4.00       5.0  
Food and drink                         2.00      3.0      4.00       5.0  
Gate location                          2.00      3.0      4.00       5.0  
Inflight wifi service                  2.00      3.0      4.00       5.0  
Inflight entertainment                 2.00      4.0      4.00       5.0  
Online support                         3.00      4.0      5.00       5.0  
Ease of Online booking                 2.00      4.0      5.00       5.0  
On-board service                       3.00      4.0      4.00       5.0  
Leg room service                       2.00      4.0      5.00       5.0  
Baggage handling                       3.00      4.0      5.00       5.0  
Checkin service                        3.00      3.0      4.00       5.0  
Cleanliness                            3.00      4.0      5.00       5.0  
Online boarding                        2.00      4.0      4.00       5.0  
Departure Delay in Minutes             0.00      0.0     12.00    1592.0  
Arrival Delay in Minutes               0.00      0.0     13.00    1584.0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   id                                 129880 non-null  int64  
 1   satisfaction_v2                    129880 non-null  object 
 2   Gender                             129880 non-null  object 
 3   Customer Type                      129880 non-null  object 
 4   Age                                129880 non-null  int64  
 5   Type of Travel                     129880 non-null  object 
 6   Class                              129880 non-null  object 
 7   Flight Distance                    129880 non-null  int64  
 8   Seat comfort                       129880 non-null  int64  
 9   Departure/Arrival time convenient  129880 non-null  int64  
 10  Food and drink                     129880 non-null  int64  
 11  Gate location                      1298

In [22]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print('----------------------------------')

id
[ 11112 110278 103199 ... 125368    251  84566]
----------------------------------
satisfaction_v2
['satisfied' 'neutral or dissatisfied']
----------------------------------
Gender
['Female' 'Male']
----------------------------------
Customer Type
['Loyal Customer' 'disloyal Customer']
----------------------------------
Age
[65 47 15 60 70 30 66 10 56 22 58 34 62 35 13 52 55 28  9 25 53 16 64 42
 21 20 26 48 57 31 17 33 32 38 29 24 37  7 39 11 49  8 40 45 67 59 44 69
 51 18 23 12 46 41 54 27 63 61 36 50 68 19 14 43 72 71 80 77 85 78 75 79
 74 73 76]
----------------------------------
Type of Travel
['Personal Travel' 'Business travel']
----------------------------------
Class
['Eco' 'Business' 'Eco Plus']
----------------------------------
Flight Distance
[ 265 2464 2138 ... 5832 5120 4260]
----------------------------------
Seat comfort
[0 1 4 5 2 3]
----------------------------------
Departure/Arrival time convenient
[0 1 2 3 4 5]
----------------------------------
Food and drink


In [23]:
df.columns = df.columns.str.lower()\
                .str.replace(' ', '_')\
                .str.replace('/', '_or_')\
                .str.replace('satisfaction_v2', 'satisfaction')

In [24]:
df.columns.to_list()

['id',
 'satisfaction',
 'gender',
 'customer_type',
 'age',
 'type_of_travel',
 'class',
 'flight_distance',
 'seat_comfort',
 'departure_or_arrival_time_convenient',
 'food_and_drink',
 'gate_location',
 'inflight_wifi_service',
 'inflight_entertainment',
 'online_support',
 'ease_of_online_booking',
 'on-board_service',
 'leg_room_service',
 'baggage_handling',
 'checkin_service',
 'cleanliness',
 'online_boarding',
 'departure_delay_in_minutes',
 'arrival_delay_in_minutes']

In [31]:
string_cols = list(df.select_dtypes('object').columns)

for col in string_cols:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [32]:
for col in string_cols:
    print(col)
    print(df[col].unique())
    print('----------------------------------')

satisfaction
['satisfied' 'neutral_or_dissatisfied']
----------------------------------
gender
['female' 'male']
----------------------------------
customer_type
['loyal_customer' 'disloyal_customer']
----------------------------------
type_of_travel
['personal_travel' 'business_travel']
----------------------------------
class
['eco' 'business' 'eco_plus']
----------------------------------


In [33]:
df.isnull().sum()

id                                        0
satisfaction                              0
gender                                    0
customer_type                             0
age                                       0
type_of_travel                            0
class                                     0
flight_distance                           0
seat_comfort                              0
departure_or_arrival_time_convenient      0
food_and_drink                            0
gate_location                             0
inflight_wifi_service                     0
inflight_entertainment                    0
online_support                            0
ease_of_online_booking                    0
on-board_service                          0
leg_room_service                          0
baggage_handling                          0
checkin_service                           0
cleanliness                               0
online_boarding                           0
departure_delay_in_minutes      

In [34]:
df.isna().sum()

id                                        0
satisfaction                              0
gender                                    0
customer_type                             0
age                                       0
type_of_travel                            0
class                                     0
flight_distance                           0
seat_comfort                              0
departure_or_arrival_time_convenient      0
food_and_drink                            0
gate_location                             0
inflight_wifi_service                     0
inflight_entertainment                    0
online_support                            0
ease_of_online_booking                    0
on-board_service                          0
leg_room_service                          0
baggage_handling                          0
checkin_service                           0
cleanliness                               0
online_boarding                           0
departure_delay_in_minutes      

In [ ]:
na_index = list(df[df['arrival_delay_in_minutes'].isnull()].index)

In [54]:
df_no_null = df.dropna()
df_fill_zero = df.fillna(0)
df_ffill = df.ffill()
df_bfill = df.bfill()

df_interpolate = df.copy(deep=True)
df_interpolate['arrival_delay_in_minutes'] = df_interpolate['arrival_delay_in_minutes'].interpolate(limit_area='inside')